### ISSUE TITLE
Idées de comment améliorer les ateliers

### ISSUE THREAD

**Issue by Nhqml** [prologin/ateliers#5]
Plusieurs idées possibles pour permettre de faire les ateliers plus en autonomie (avec moins d'orgas / moins de suivi) :
1. Faire une intro / un cours devant toute la classe pour leur expliquer les bases de Python / micro:bit / whatever puis les lâchers sur les TP
2. Faire un live coding sur des fonctionnalités "simples" de l'atelier puis les laisser améliorer (en leur donnant des idées)

**Comment by alarsyo** [comment]
Je sais pas si c'est forcément faisable en toutes circonstances, typiquement hier c'était impossible de faire tes deux propositions.

**Comment by Nhqml** [comment]
Oui

**Comment by rissson** [comment]
Imported into https://gitlab.com/prologin/ateliers/contenus/site/-/issues/1
