### ISSUE TITLE
Découpage étape par étape des ateliers

### ISSUE THREAD

**Issue by alarsyo** [prologin/ateliers#6]
Je rebondis sur les deux issues ouvertes pour discuter comment améliorer les ateliers, avec l'expérience de ceux d'hier à 42.

Pour moi ce qu'il faut le plus modifier, c'est le fait qu'actuellement les ateliers décrivent un résultat attendu, plus qu'ils ne guident vers ce résultat. On leur donne des exemples de fonctions par ci par là, mais pour des grands débutants il faut plus que ça, ce qui leur manque surtout c'est comment articuler toutes ces fonctions qu'on leur donne de manière logique.

Pour moi il faut une approche où on leur tient vraiment la main, en les encourageant à expérimenter par eux même de temps en temps mais de manière très soft :

- il faut que la plupart du temps ils aient un exemple de code complet ou quasi-complet à copier coller dans leur fichier, parce qu'ils sont clairement pas prêts à raisonner et écrire du code en autonomie (et c'est normal en 1h d'atelier ; mieux vaut leur montrer que c'est fun même si pour le moment ils se contentent de copier coller beaucoup de choses)
- il faut que toutes ces étapes produisent un résultat observable, pour que ce soit un peu gratifiant (j'ai vu plusieurs personnes partir à la fin parce qu'on bouclait l'atelier, qui avaient passé une heure à remplir le code à trou Flappy Bird sans rien pouvoir tester sur le microbit parce qu'il leur manquait toute la logique entre les fonctions encore. J'ai rushé le truc pour quelques uns qui ont pu voir un tuyau passer de droite à gauche, mais c'est tout).

Donc j'imagine plutôt quelque chose où on leur fait faire des petites choses étapes par étape, avec chaque étape qui est un vrai accomplissement en soit. Exemple pour télémoticônes : 

1. On leur montre comment juste afficher une image avec `display.show`
2. On leur montre comment changer cette image, clear l'écran, mettre des pauses avec sleep entre les images
3. On leur montre comment afficher du texte à l'écran
4. On leur fait allumer la radio et envoyer simplement un message texte à un autre microbit, et comment le recevoir sur l'autre
5. On leur montre comment encoder l'image par magie pour l'envoyer par radio
6. S'ils sont arrivés jusqu'ici, on peut partir sur le fait qu'un microbit fasse émetteur **et** récepteur, et rajouter le choix d'une image différente dans une liste avec les boutons, etc

En pratique c'est comme ça qu'on procédait hier, mais ça nécessitait un orga pour mener le truc tout du long, alors que c'est des étapes qu'on peut très facilement lister dans le sujet de l'atelier

**Comment by rissson** [comment]
Imported into https://gitlab.com/prologin/ateliers/contenus/site/-/issues/3
